name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
assignees:
  - Virtuoel
body:
  - type: markdown
    attributes:
      value: |
        Remember to include a crash log if this bug caused the game to crash!
  - type: dropdown
    id: mc_version
    attributes:
      label: What Minecraft version(s) did you experience this bug on?
      description: You may select more than one.
      multiple: true
      options:
        - 1.14.4
        - 1.15.2
        - 1.16.5
        - 1.17.1
        - Other (specify below)
    validations:
      required: true
  - type: input
    id: other_mc_version
    attributes:
      label: Minecraft version (if not in the above list)
      description: Fill in if you selected `Other` above
      placeholder: (e.g. 1.17 Snapshot 21w21a, e.g. 1.18 Experimental Snapshot 1)
    validations:
      required: false
  - type: dropdown
    id: mod_loader
    attributes:
      label: Mod loader
      description: What mod loader were you using?
      options:
        - Fabric
        - Forge
    validations:
      required: true
  - type: input
    id: mod_loader_version
    attributes:
      label: Mod loader version
      description: What Fabric Loader version (not Fabric API) or Forge version were you using?
      placeholder: (e.g. Fabric Loader 0.11.6, e.g. Forge 36.1.62)
    validations:
      required: true
  - type: input
    id: fabric_api_version
    attributes:
      label: Fabric API version (if applicable)
      description: "What Fabric API version (not Fabric Loader) were you using?\n
      (Fill in if you selected the Fabric mod loader and this mod requires Fabric API)"
      placeholder: (e.g. Fabric API 0.37.0)
    validations:
      required: false
  - type: textarea
    id: the_problem
    attributes:
      label: What went wrong? (Crash logs don't go in this box)
      description: What did you expect to happen, and what happened instead?
      placeholder: Tell us what you saw!
    validations:
      required: true
  - type: textarea
    id: other_mods
    attributes:
      label: Installed mods
      description: What mods were you running at the time? (Make sure to include their version numbers, including this mod's version!)
      placeholder: Put your full mod list here! (sometimes visible in the launcher's logs for easy copy-pasting)
    validations:
      required: true
  - type: textarea
    id: crash_logs
    attributes:
      label: Full crash log contents (if any)
      description: "Crash log files are typically found within the `.minecraft/crash-reports/` folder in a file with a name similar to `crash-20xx-xx-xx_xx.xx.xx-client.txt`.\n
      If there are multiple, make sure to select the one that corresponds to when you crashed (possibly the most recent file).\n
      Please copy the full contents of the crash log and paste it under the `<p>` line below."
      value: "<details>\n<summary>Crash log output:</summary>\n<p>\n\n"

