# Copyright (c) 2021 Virtuoel. All Rights Reserved.

name: Suggestion
description: Suggest a change or enhancement
title: "[Suggestion]: Untitled suggestion"
labels: [enhancement]
assignees:
  - Virtuoel
body:
  - type: markdown
    attributes:
      value: "Write a title for your suggestion above!\n\n"
  - type: textarea
    id: suggestion
    attributes:
      label: What do you want to suggest?
